src/auth.py
from flask import session, Blueprint, request, render_template, flash, redirect, url_for, current_app
from werkzeug.security import check_password_hash, generate_password_hash
import re
from bson.objectid import ObjectId

auth = Blueprint('auth', __name__, template_folder='../templates')

def create_user(mongo, user_data):
    user_data['profile_pic'] = user_data.get('profile_pic', 'default_profile.jpeg')
    mongo.cx['CE-301'].users.insert_one(user_data)  # Insert into "users" collection

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email'].lower()  # Convert email to lowercase
        password = request.form['password']
        print(f"Login attempt with email: {email}")  # Debug statement
        if authenticate_user(current_app.mongo, email, password):
            print("Authentication successful")  # Debug statement
            flash('Login successful!', category='success')
            user_data = current_app.mongo.cx['CE-301'].users.find_one({'email': email})
            session['user_id'] = str(user_data['_id'])  # Store user ID in session
            session['username'] = user_data['username']
            return redirect(url_for('user.dashboard'))
        else:
            print("Authentication failed")  # Debug statement
            flash('Alert: Incorrect username or password. Please try again.', category='error')
    return render_template('login.html')

@auth.route('/logout')
def logout():
    session.clear()  # Clear the session to log out the user
    flash('You have been logged out.', category='info')
    return redirect(url_for('auth.login'))

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email'].lower()  # Convert email to lowercase
        password = request.form['password']
        print(f"Signup attempt with email: {email}, username: {username}")  # Debug statement
        if not username or not email or not password:
            flash('Please fill out all fields', category='error')
        else:
            if len(password) < 8 or not re.search("[a-z]", password) or not re.search("[A-Z]", password) or not re.search("[0-9]", password) or not re.search("[!@#$%^&*]", password):
                flash('Alert: Password must be at least 8 characters long and include a mix of letters, numbers, and symbols', category='error')
            else:
                mongo = current_app.mongo
                user_exists = mongo.cx['CE-301'].users.find_one({'email': email})
                if user_exists:
                    flash('Alert: Email address already in use', category='error')
                else:
                    bcrypt = current_app.bcrypt
                    hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
                    user_data = {'username': username, 'email': email, 'password': hashed_password, 'profile_pic': 'default_profile.jpeg'}
                    create_user(mongo, user_data)
                    print("User registered successfully")  # Debug statement
                    flash('Registration successful! Please log in.', category='success')
                    return redirect(url_for('auth.login'))
        
    return render_template('signup.html')

def authenticate_user(mongo, email, password):
    print(f"Attempting to authenticate user with email: {email}")  # Debug statement
    user = mongo.cx['CE-301'].users.find_one({"email": email})  # Retrieve from "users" collection
    print(f"Query executed. Result: {user}")  # Debug statement
    if user:
        print(f"User found: {user}")  # Debug statement
        bcrypt = current_app.bcrypt
        if bcrypt.check_password_hash(user['password'], password):
            session['user_id'] = str(user['_id'])  # Store user ID as a string
            print(f"User authenticated: {user['_id']}")  # Debug statement
            return True
        else:
            print("Password check failed")  # Debug statement
    else:
        print("User not found")  # Debug statement
    return False

templates/auth.base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="flash-messages">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {% if category == 'success' %}
                                <i class="fas fa-check-circle"></i>
                            {% elif category == 'error' %}
                                <i class="fas fa-exclamation-circle"></i>
                            {% elif category == 'info' %}
                                <i class="fas fa-info-circle"></i>
                            {% endif %}
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/cashflow.html
{% extends "base.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Cash Flow</h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <form method="POST">
          <div class="form-group row">
            <label for="initial_cash" class="col-sm-3 col-form-label">Initial Cash Amount:</label>
            <div class="col-sm-9">
              <input type="number" step="0.01" class="form-control" id="initial_cash" name="initial_cash" value="{{ initial_cash }}" required>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </div>
        </form>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">Total Transaction:</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" value="{{ total_transaction }}" readonly>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">Total Repayment Amount (Credit Card):</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" value="{{ total_repayment_amount }}" readonly>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">Net Cash Flow:</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" value="{{ net_cash_flow }}" readonly>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/chatbot.html
{% extends "base.html" %}
{% block content %}

<style>
    /* Container for the entire chat interface */
    .chat {
        border-radius: 15px;
        background-color: #f8f9fa;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1); /* Subtle shadow for a clean, modern look */
    }

    /* Chat message area */
    .msg_card_body {
        overflow-y: auto;
        height: 600px; /* Ensuring enough space for messages */
        border-radius: 15px;
    }

    /* User message bubbles */
    .msg_cotainer_send {
        background-color: #05728f;
        color: white;
        border-radius: 10px;
        padding: 10px;
        position: relative;
        max-width: 80%; /* Control bubble width */
        margin-bottom: 10px;
        margin-left: auto; /* Align user messages to the right */
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1); /* Light shadow */
    }

    /* Chatbot message bubbles */
    .msg_cotainer {
        background-color: #ececec;
        border-radius: 10px;
        padding: 10px;
        position: relative;
        max-width: 80%; /* Control bubble width */
        margin-bottom: 10px;
        margin-right: auto; /* Align bot messages to the left */
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1); /* Light shadow */
    }

    /* Message time display */
    .msg_time, .msg_time_send {
        position: absolute;
        bottom: -15px;
        font-size: 10px;
        color: gray;
    }

    .msg_time_send {
        right: 0;
    }

    .msg_time {
        left: 0;
    }

    /* Send button styling */
    .send_btn {
        background-color: #05728f;
        color: white;
    }

    .send_btn:hover {
        background-color: #045a6f;
    }

    .input-group-text {
        border: none;
        cursor: pointer;
    }

    /* Loading spinner */
    .loading {
        display: flex;
        justify-content: center;
        padding: 20px;
    }

    .loader {
        border: 5px solid #f3f3f3;
        border-top: 5px solid #3498db;
        border-radius: 50%;
        width: 30px;
        height: 30px;
        animation: spin 1s linear infinite;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card chat">
                <div class="card-header msg_head">
                    <div class="d-flex bd-highlight">
                        <div class="img_cont">
                            <!-- <img src="{{ url_for('static', filename='logo.jpeg') }}" class="rounded-circle user_img"> -->
                            <span class="online_icon"></span>
                        </div>
                        <div class="user_info">
                            <span>ChatBot</span>
                            <p>Ask me anything!</p>
                        </div>
                    </div>
                </div>
                <div id="messageFormeight" class="card-body msg_card_body">
                    <!-- Chat messages will be appended here -->
                </div>
                <div class="loading">
                    <div id="loading" class="loader" style="display: none;"></div>
                </div>
                <div class="card-footer">
                    <form id="messageArea" class="input-group">
                        <input type="text" id="text" name="msg" placeholder="Type your message..." autocomplete="off" class="form-control type_msg" required/>
                        <div class="input-group-append">
                            <button type="submit" id="send" class="input-group-text send_btn"><i class="fas fa-paper-plane"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Include jQuery and Bootstrap JS -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function() {
        $("#messageArea").on("submit", function(event) {
            event.preventDefault(); // Prevent the form from submitting normally
            
            const date = new Date();
            const hour = date.getHours();
            const minute = date.getMinutes().toString().padStart(2, '0');
            const str_time = hour + ":" + minute;
            var rawText = $("#text").val();

            if (rawText.trim() === '') {
                return; // Do not send empty messages
            }

            // Display user's message
            var userHtml = '<div class="d-flex justify-content-end mb-4"><div class="msg_cotainer_send">' + rawText + '<span class="msg_time_send">' + str_time + '</span></div><div class="img_cont_msg"></div></div>';
            $("#messageFormeight").append(userHtml);
            $("#text").val(""); // Clear the text input field

            // Scroll to the bottom of the chat container
            $("#messageFormeight").animate({ scrollTop: $("#messageFormeight")[0].scrollHeight }, 1000);

            // Show loading indicator
            $("#loading").show();

            // Send message to the server via AJAX
            $.ajax({
                url: "{{ url_for('chatbot.chatbot') }}", // Use Flask's url_for to get the correct URL
                type: "POST",
                contentType: "application/json",
                data: JSON.stringify({ user_query: rawText }),
                success: function(data) {
                    // Hide loading indicator
                    $("#loading").hide();

                    // Display bot's response
                    var botHtml = '<div class="d-flex justify-content-start mb-4"><div class="img_cont_msg"></div><div class="msg_cotainer">' + data.response + '<span class="msg_time">' + str_time + '</span></div></div>';
                    $("#messageFormeight").append(botHtml);

                    // Scroll to the bottom after the bot's response
                    $("#messageFormeight").animate({ scrollTop: $("#messageFormeight")[0].scrollHeight }, 1000);
                },
                error: function(error) {
                    console.error('Error:', error);
                    $("#loading").hide();

                    // Display error message
                    var errorHtml = '<div class="d-flex justify-content-start mb-4"><div class="img_cont_msg"></div><div class="msg_cotainer">An error occurred. Please try again.<span class="msg_time">' + str_time + '</span></div></div>';
                    $("#messageFormeight").append(errorHtml);

                    // Scroll to the bottom in case of error
                    $("#messageFormeight").animate({ scrollTop: $("#messageFormeight")[0].scrollHeight }, 1000);
                }
            });
        });
    });
</script>
    
{% endblock %}

templates/creditCard.html
<!-- templates/creditCard.html -->
{% extends "base.html" %}

{% block title %}
Credit Card - Net Plus
{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">

<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="dashboard_graph">
            <div class="row x_title">
                <div class="col-md-6">
                    <h3>Credit Card Transactions</h3>
                </div>
                <div class="col-md-6">
                    <div class="btn-group float-right">
                        <!-- You can add buttons or dropdowns here -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Transactions Overview Panel -->
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Transactions Overview<small>Manage your credit card expenses</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="card-box table-responsive">
                    <p class="text-muted font-13 m-b-30">
                        Use the table below to view, filter, and manage your credit card expenses.
                    </p>
                    <table id="creditCardTransactionsTable" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Type</th>
                                <th>Category</th>
                                <th>Date</th>
                                <th>Description</th>
                                <th>Total Outstanding Amount</th>
                                <th>Remaining Outstanding</th>
                                <th>Repayment Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for transaction in credit_card_transactions %}
                            <tr>
                                <td>{{ transaction.type }}</td>
                                <td>{{ transaction.category }}</td>
                                <td>{{ transaction.date.strftime('%Y-%m-%d') }}</td>
                                <td>{{ transaction.description }}</td>
                                <td>{{ transaction.amount | format_with_commas }}</td>
                                <td>{{ transaction.remaining_amount|default(transaction.amount)|format_with_commas }}</td>
                                <td class="{{ 'text-success' if transaction.repayment_status == 'Paid' else 'text-danger' }}">{{ transaction.repayment_status }}</td>
                                <td>
                                    <button class="btn btn-warning btn-sm repayment-btn" title="Repayment" data-transaction-id="{{ transaction._id }}" data-remaining-amount="{{ transaction.remaining_amount if transaction.remaining_amount is not none else transaction.amount }}" {% if transaction.repayment_status == 'Paid' %}disabled{% endif %}>
                                        <i class="fa fa-hand-holding-usd"></i>
                                    </button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Repayment Overview Panel -->
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Repayments Overview<small>Track your repayments</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="card-box table-responsive">
                    <p class="text-muted font-13 m-b-30">
                        Use the table below to view, filter, and manage your repayments.
                    </p>
                    <table id="creditCardRepaymentsTable" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Category</th>
                                <th>Date</th>
                                <th>Description</th>
                                <th>Repayment Date</th>
                                <th>Repayment Amount</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for transaction in credit_card_transactions %}
                                {% for repayment in transaction.repayments %}
                                <tr>
                                    <td>{{ transaction.category }}</td>
                                    <td>{{ transaction.date.strftime('%Y-%m-%d') }}</td>
                                    <td>{{ transaction.description }}</td>
                                    <td>{{ repayment.repayment_date.strftime('%Y-%m-%d') }}</td>
                                    <td>{{ repayment.repayment_amount | format_with_commas }}</td>
                                    <td>
                                        <form action="{{ url_for('credit_card.delete_repayment') }}" method="post" style="display:inline;">
                                            <input type="hidden" name="repayment_id" value="{{ repayment._id }}">
                                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                {% endfor %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="repaymentForm" class="sidebar">
    <div class="sidebar-content">
        <button class="btn btn-secondary close-btn" id="closeFormBtn">&times;</button>
        <h2>Update Repayment</h2>
        <form id="repaymentFormContent" action="{{ url_for('credit_card.update_repayment') }}" method="POST">
            <input type="hidden" name="transaction_id" id="transaction_id">
            <div class="form-group">
                <label for="outstanding_amount">Total Outstanding Amount</label>
                <input type="text" id="outstanding_amount" class="form-control" readonly>
            </div>
            <div class="form-group">
                <label for="remaining_amount">Remaining Outstanding Amount</label>
                <input type="text" id="remaining_amount" class="form-control" readonly>
            </div>
            <div class="form-group">
                <label for="repayment_date">Repayment Date</label>
                <input type="date" id="repayment_date" class="form-control" name="repayment_date" required>
            </div>            
            <div class="form-group">
                <label for="repayment_amount">Repayment Amount</label>
                <input type="number" id="repayment_amount" class="form-control" name="repayment_amount" step="0.01" required>
            </div>
            <div class="form-group">
                <label for="repayment_status">Repayment Status</label>
                <input type="text" id="repayment_status" class="form-control" name="repayment_status" readonly>
            </div>
            <button type="submit" class="btn btn-primary">Update Repayment</button>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<style>
    .sidebar {
        height: 100%;
        width: 0;
        position: fixed;
        z-index: 1;
        top: 0;
        right: 0;
        background-color: #f8f9fa;
        overflow-x: hidden;
        transition: width 0.5s;
        padding-top: 60px;
    }

    .sidebar-content {
        padding: 15px;
    }

    .sidebar.open {
        width: 400px; /* Width of the sidebar */
    }

    #mainContent {
        transition: margin-right 0.5s;
    }

    .container-fluid {
        padding-right: 0;
    }

    .text-success {
        color: green;
    }

    .text-danger {
        color: red;
    }

    .dataTables_wrapper .dataTables_filter label::before {
        content: '\f002'; /* Unicode for Font Awesome search icon */
        font-family: FontAwesome;
        padding-right: 5px;
    }
</style>

<script>
    $(document).ready(function() {
        // Initialize DataTables with additional options for the main transactions table
        $('#creditCardTransactionsTable').DataTable({
            "paging": true,
            "lengthChange": true,  // This enables the "Show entries" dropdown
            "lengthMenu": [10, 25, 50, 100],  // Options for "Show entries"
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "columnDefs": [{
                "targets": -1,  // Disable ordering on the "Actions" column
                "orderable": false,
            }]
        });

        // Initialize DataTables with additional options for the repayments table
        $('#creditCardRepaymentsTable').DataTable({
            "paging": true,
            "lengthChange": true,
            "lengthMenu": [10, 25, 50, 100],
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "columnDefs": [{
                "targets": -1,
                "orderable": false,
            }]
        });
    });

    document.querySelectorAll('.repayment-btn').forEach(button => {
        button.addEventListener('click', function() {
            var transactionId = this.getAttribute('data-transaction-id');
            var remainingAmount = this.getAttribute('data-remaining-amount');
            var row = this.closest('tr');
            var outstandingAmount = row.querySelector('td:nth-child(5)').textContent;
            var repaymentStatus = row.querySelector('td:nth-child(7)').textContent;
            var repaymentForm = document.getElementById('repaymentForm');
            var mainContent = document.getElementById('mainContent');
            document.getElementById('transaction_id').value = transactionId;
            document.getElementById('outstanding_amount').value = outstandingAmount;
            document.getElementById('remaining_amount').value = remainingAmount;
            document.getElementById('repayment_status').value = repaymentStatus;
            repaymentForm.classList.add('open');
            mainContent.style.marginRight = "400px";
        });
    });

    document.getElementById('closeFormBtn').addEventListener('click', function() {
        var repaymentForm = document.getElementById('repaymentForm');
        var mainContent = document.getElementById('mainContent');
        repaymentForm.classList.remove('open');
        mainContent.style.marginRight = "0";
    });
</script>

{% endblock %}

templates/login.html
{% extends "auth.base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="flex-r container">
    <div class="flex-r login-wrapper">
        <div class="login-text">
            <div class="logo">
                <i class="fas fa-coins"></i>
                <span>NetPlus</span>
            </div>
            <h1 style="margin-bottom: 10px;">Sign In</h1>
            <p>Ready to take control of your financial future? Let's log in!</p>

            <form class="flex-c" action="{{ url_for('auth.login') }}" method="post">
                <div class="input-box">
                    <span class="label">E-mail</span>
                    <div class="flex-r input">
                        <input type="text" name="email" placeholder="user@gmail.com" required>
                        <i class="fas fa-paper-plane"></i>
                    </div>
                </div>
                
                <div class="input-box">
                    <span class="label">Password</span>
                    <div class="flex-r input">
                        <input type="password" name="password" placeholder="At least 8 characters (e.g., P@ssw0rd!)" required>
                        <i class="fas fa-lock"></i>
                    </div>
                </div>

                <input class="btn" type="submit" value="Sign In" style="margin-bottom: 20px;">
                <span class="extra-line">
                    <span>Don't have an account?</span>
                    <a href="{{ url_for('auth.signup') }}">Sign Up</a>
                </span>
            </form>

        </div>
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends "auth.base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="flex-r container">
    <div class="flex-r login-wrapper">
        <div class="login-text">
            <div class="logo">
                <i class="fas fa-coins"></i>
                <span>NetPlus</span>
            </div>
            <h1 style="margin-bottom: 10px;">Sign Up</h1>
            <p>Empower yourself by taking control of your financial future today.</p>

            <form class="flex-c" action="{{ url_for('auth.signup') }}" method="post">
                <div class="input-box">
                    <span class="label">Username</span>
                    <div class="flex-r input">
                        <input type="text" name="username" placeholder="Your username (e.g., User123)" required>
                        <i class="fas fa-user-circle"></i>
                    </div>
                </div>

                <div class="input-box">
                    <span class="label">E-mail</span>
                    <div class="flex-r input">
                        <input type="email" name="email" placeholder="user@gmail.com" required>
                        <i class="fas fa-paper-plane"></i>
                    </div>
                </div>
                
                <div class="input-box">
                    <span class="label">Password</span>
                    <div class="flex-r input">
                        <input type="password" name="password" placeholder="At least 8 characters (e.g., P@ssw0rd!)" required>
                        <i class="fas fa-lock"></i>
                    </div>
                </div>

                <div class="check">
                    <input type="checkbox" name="terms" id="terms" required>
                    <label for="terms">I agree to the Terms and Conditions</label>
                </div>

                <input class="btn" type="submit" value="Create Account">
                <span class="extra-line">
                    <span>Already have an account?</span>
                    <a href="{{ url_for('auth.login') }}">Sign In</a>
                </span>
            </form>

        </div>
    </div>
</div>
{% endblock %}